apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingdata-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratingdata-service
  template:
    metadata:
      labels:
        app: ratingdata-service
    spec:
      containers:
      - name: ratingdata
        image: ratingdata-service:v1
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5