apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingdata-deploy
  namespace: default
  labels:
    app: ratingdata-service
    version: ${IMAGE_TAG}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratingdata-service
  template:
    metadata:
      labels:
        app: ratingdata-service
        version: ${IMAGE_TAG}
    spec:
      containers:
      - name: ratingdata
        image: ${DOCKER_USER}/ratingdata-service:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10