apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieinfo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movieinfo-service
  template:
    metadata:
      labels:
        app: movieinfo-service
    spec:
      containers:
      - name: movieinfo
        image: movieinfo-service:v1
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5